### ISSUE TITLE
plane rotation

### ISSUE THREAD

**Issue by HassanAouchev** [fdlombae/FlyFish#2]
I tried plane rotation and I think it doesn't work using flyfish I tried the exact same rotation in MATLAB with the same motor and then it worked like I wanted to.

I rotated around e12 so 
Motor rotation = Motor::rotation(45,TwoBlade{0,0,0,0,0,1});
newPlane = rotation * OneBlade{0,1,1,0} * ~rotation;. 

This should give a plane that is rotated 45 degrees but it doesn't.

**Comment by JelleAdyns** [comment]
I'm experiencing the same issue. The planes stay the same after rotation.

**Comment by HassanAouchev** [comment]
the issue is fixed you need to download the new version of flyfish on github.

**Comment by JelleAdyns** [comment]
I already did, but it still doesn't work for me. Maybe I'm doing something wrong.

Motor rotation = Motor::Rotation(45, TwoBlade{ 0,0,0,0,1,0 });
auto newPlane = (rotation * OneBlade{ 0,1,1,0 } * ~rotation).Grade1();

newPlane results into OneBlade{0,1,1,0} which shouldn't be the case right?

**Comment by HassanAouchev** [comment]
You are right it doesn't work. You should mail Flor because he should have fixed it normally but I just tested it out and it doesn't work for me too.

**Comment by JelleAdyns** [comment]
Alright, I'll do it right away. Thanks for confirming!

**Comment by JelleAdyns** [comment]
I managed to kind of locate the issue.

When I use a Multivector like this, the rotation actually works like intended:

     MultiVector rot{};
     rot = (-sin(90 * DEG_TO_RAD / 2) * m_RotationLine.Normalized());
     rot[0] = cos(90 * DEG_TO_RAD / 2);

     m_StartPlane = (rot * m_StartPlane * ~rot).Grade1();

But when i use the motor, the geometric product gets messed up:

     Motor rot = Motor::Rotation(90, m_RotationLine);
     m_StartPlane = (rot * m_StartPlane * ~rot).Grade1();
     
The values in the Multivector and the Motor are exactly the same, so the issue must lie within Motor::operator*(OneBlade).

**Comment by JelleAdyns** [comment]
I think I found the problem!

This is the renewed function. Can you let me know if it works for you too?

```
[[nodiscard]] MultiVector Motor::operator* (const OneBlade& b) const
{
    MultiVector res{};
      res[1] = data[0] * b[0] + data[1] * b[1] + data[2] * b[2] + data[3] * b[3];
      res[2] = data[0] * b[1] + data[6] * b[2] - data[5] * b[3];
      res[3] = -data[6] * b[1] + data[0] * b[2] + data[4] * b[3];
      res[4] = data[5] * b[1] - data[4] * b[2] + data[0] * b[3];
      res[11] = -data[4] * b[0] + data[7] * b[1] + data[3] * b[2] - data[2] * b[3];
      res[12] = -data[5] * b[0] - data[3] * b[1] + data[7] * b[2] + data[1] * b[3];
      res[13] = -data[6] * b[0] + data[2] * b[1] - data[1] * b[2] + data[7] * b[3];
      res[14] = data[4] * b[1] + data[5] * b[2] + data[6] * b[3] ;
    return res;

  //previous version:
    //MultiVector res{};
    //res[1] = data[0] * b[0] - data[1] * b[1] - data[2] * b[2] - data[3] * b[3];
    //res[2] = data[0] * b[1] - data[6] * b[2] + data[5] * b[3];
    //res[3] = data[6] * b[1] + data[0] * b[2] - data[4] * b[3];
    //res[4] = -data[5] * b[1] + data[4] * b[2] + data[0] * b[3];
    //res[11] = -data[4] * b[0] + data[7] * b[1] + data[3] * b[2] - data[2] * b[3];
    //res[12] = -data[5] * b[0] - data[3] * b[1] + data[7] * b[2] + data[1] * b[3];
    //res[13] = -data[6] * b[0] + data[2] * b[1] - data[1] * b[2] + data[7] * b[3];
    //res[14] = data[4] * b[1] + data[5] * b[2] + data[6] * b[3];
    //return res;
}

```
---------------------
(PS: Note that following function might be different than yours. **This makes sure i don't need to translate to the origin and back.**
This will not a problem)

```
[[nodiscard]] static Motor Rotation(float angle, const TwoBlade line)
{
    float mult{ -sin(angle * DEG_TO_RAD / 2) / line.Norm() };
    return Motor{
        cos(angle * DEG_TO_RAD /2),
        mult * line[0],
        mult * line[1],
        mult * line[2],
        mult * line[3],
        mult * line[4],
        mult * line[5],
        0
    };
}
```
Normal version:
```
[[nodiscard]] static Motor Rotation(float angle, const TwoBlade line)
{
    float mult{ -sin(angle * DEG_TO_RAD / 2) / line.Norm() };
    return Motor{
        cos(angle * DEG_TO_RAD /2),
        0,
        0,
        0,
        mult * line[3],
        mult * line[4],
        mult * line[5],
        0
    };
}
```

**Comment by HassanAouchev** [comment]
ill test it out later but if it works for you it should also work for me.

**Comment by JelleAdyns** [comment]
Alright, sounds good.

If it works, it's best that you still stick with the original version until the teachers approve.
This works with original version:
```
MultiVector rot{};
 rot = (-sin(90 * DEG_TO_RAD / 2) * m_RotationLine.Normalized());
 rot[0] = cos(90 * DEG_TO_RAD / 2);

 m_StartPlane = (rot * m_StartPlane * ~rot).Grade1();
```

**Comment by fdlombae** [comment]
There was still a bug in the motor gep oneblade.
Thanks for bringing this to my attention. It is fixed in latest bug fixes!
